name = "ryanbrewerdev"
version = "0.1.0"
description = "A Gleam project"
target = "javascript"
gleam = ">= 1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 1.0.0"
lustre = ">= 4.3.1 and < 5.0.0"
party = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_ssg = ">= 0.8.0 and < 1.0.0"
